Repository ionos-cloud/cluster-api-provider-proxmox, pull requests merged in 2024-06, with the labels that each got.

#233 cluster-template-external-creds: Fix name of the Secret
  templates/cluster-template-external-creds.yaml
Labels: kind/bug, go

#235 mockery: don't use boilerplate
  .mockery.yaml
Labels: kind/bug, skip e2e

#244 Remove unnecessary config
  docs/Usage.md
Labels: skip e2e

#250 release v0.5.1
  clusterctl-settings.json
Labels: skip e2e
